import Head from 'next/head'
import {BsMedium, BsLinkedin, BsFillRocketTakeoffFill,BsFillMoonStarsFill } from"react-icons/bs"
import {SiQuora} from 'react-icons/si'
import Image from "next/image";
import devm from '../public/mk-3d.png';
import todo from "../public/todo.png";
import pizza from "../public/pizza.jpg";
import tribute from "../public/tribute.jpg";
import college from "../public/college.jpg";
import rocket from "../public/rocket.jpg";
import voice from "../public/voice_reco.png";
import education from "../public/education.jpg";
export default function Home() {
  return (
    <>
      <Head>
        <title>Manpreet Kaur Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='bg-pink-200 px-10'>
        <section className=' min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons'>developedbyM</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className="bg-gradient-to-r from-green-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8" href="#">Resume</a></li>
            </ul>
          </nav>
          <div className='text-center  p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium'>Manpreet Kaur</h2>
            <h3 className='text-2xl py-2'>Developer and Student.</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
            An astronomy and coding enthusiast, with a positive mindset. A person who loves working on new ideas and building real life solutions using coding. Fast and proficient learner. 
            Adapts quickly to the work environment. 
            </p>
          </div>
          <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
            
            <BsLinkedin/>
            <SiQuora/>
            <BsMedium/>
          </div>
          <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20'>
            <Image src={devm} layout='fill' objectFit='cover'/>
          </div>
          
        </section>
        {/*  */}
        <section >
          <div className='pt-10 ' >
            <h3 className='text-3xl py-1'>Project works</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>
            As a developer with over 2 years of experience in web designing and development, and 1 year+ experience in app development, I have gained a deep understanding of the technologies and tools required for creating dynamic and responsive web applications and mobile apps. I am also currently expanding my knowledge and expertise in blockchain and web3 development.
            Here are some of my project works:
            </p>
            <div>
            <h3 className='text-center text-2xl' >Web Development </h3>
            
            <div className='flex  flex-wrap justify-center '>
              
             
              
              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={todo} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>Todo Tracker</h2>
                <p className='py-2'>A web application for keeping a track of to-dos (daily tasks). Having integrated functionalities like adding to-do items (with data and time), editing their content, storing them (in local-storage), marking them as complete (and recording completion time) and deleting them</p>
                <span className=' text-teal-600 text-center text-xl'>ReactJs, TailWindCss </span>
              </div>

              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={pizza} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>Pizzeria!</h2>
                <p className='py-2'>A pizza delivery and ordering web application with user login, logiut and order customization. Backend implemented for both Customer and Admin.</p>
                <span className=' text-teal-600 text-center text-xl'>ReactJs, MongoDB, NodeJS</span>
              </div>

              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={tribute} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>Todo Tracker</h2>
                <p className='py-2'>A tribute webpage dedicated to Mr. Bruce LEe, who is an idol to me. The page was designed using css styled components, with image carousel using javascript.</p>
                <span className=' text-teal-600 text-center text-xl'>HTML5, CSS, JavaScript</span>
              </div>
              
            </div>
            <div>
            <h3 className='text-center text-2xl' >App Development & other Softwares</h3>
            
            <div className='flex  flex-wrap justify-center '>
              
             
              
              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={college} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>College App (Team Project)</h2>
                <p className='py-2'>Working as an app developer in college app team. Designing cross platform application.	Working on front end and backend. Updating the software with each new release of Flutter UI libraries and removing deprecated libraries and components.
</p>
                <span className=' text-teal-600 text-center text-xl'>Flutter, Firebase, Postman, MongoDb, NodeJS </span>
              </div>

              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={rocket} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>ISRO Rocket DBMS</h2>
                <p className='py-2'>A database focused GUI program to help store, retrieve or manipulate data regarding rockets.</p>
                <span className=' text-teal-600 text-center text-xl'>Python, MySQL</span>
              </div>
              <div className='text-center shadow-lg p-8 rounded-xl my-10 mx-10 w-fit h-fit bg-white w-[100%] max-w-[350px]' >
                <Image className="mx-auto" src={voice} width={300} height={200} />
                <h2 className='text-lg font-medium pt-8 pb-2 '>Voice Assistant</h2>
                <p className='py-2'>An AI based program to assists user with tasks like searching on Google, listening to music, searching latest news, by just using their voice.</p>
                <span className=' text-teal-600 text-center text-xl'>Python </span>
              </div>
              

            </div>
            </div>
          </div>
          </div>
          
        </section>
        {/*  */}
        <section>
          <div  className='pt-10'>
          <h3 className='text-3xl py-1'>
            Education</h3>
            <div className='pt-10 flex flex-wrap  justify-between items-center'>
              <div  >
                <Image src={education} width={700} className=' rounded-3xl mb-6'/>
              </div>
              <div className='w-[700px] '>
                <div className=' bg-gradient-to-r from-pink-300 to-purple-300 rounded-3xl p-10 '>
                  <h3 className='text-teal-900 text-2xl'>BSc(Hons) Computer Science</h3>
                  <h2>Mata Sundri College for Women, University of Delhi</h2>
                  <p className='text-xl pt-3'>First Year CGPA: <span className='text-white'>8.2</span> </p>
                </div>
                <div className='bg-gradient-to-r from-pink-300 to-purple-300 rounded-3xl p-10 mt-7'>
                <h3 className='text-teal-900 text-2xl'>High School</h3>
                <h2>GHPS Karol Bagh</h2>
                <p className='text-xl pt-3'>12th Grade Score: <span className='text-white'>83%</span> </p>

                </div>
              </div>
            </div>
          

          </div>
        </section>
        <section>
          <div className='mt-20'>
          <h3 className='text-3xl py-1'>
            Work Experiences</h3>
            
          </div>

        </section>
        <section>
          <div className='mt-20'>
          <h3 className='text-3xl py-1'>
            Techinical Skills</h3>
          </div>
          
          
        </section>
       
      </main>
    </>
  )
}
